services:
  app:
    image: ghcr.io/remla25-team18/app:0.0.19
    container_name: app_container
    ports:
      - "4200:4200"
    depends_on:
      - model-service
    environment:
      - DNS=model-service
      - MODEL_PORT=5050
    networks:
      - app-network

  model-service:
    container_name: model_service_container
    image: ghcr.io/remla25-team18/model-service:1.0.3
    ports:
      - "5050:5050"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
