services:
  app:
    image: ghcr.io/remla25-team18/app:0.0.7
    container_name: app_container
    ports:
      - "4200:4200"
    depends_on:
      - model-service
    environment:
      - MODEL_SERVICE_URL=model-service
      - MODEL_SERVICE_PORT=5050
    networks:
      - app-network

  model-service:
    image: ghcr.io/remla25-team18/model-service:1.0.1
    container_name: model_container
    ports:
      - "5050:5050"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
