version: '3.9'

services:
  app:
    build:
      context: ../app
    container_name: app_container
    ports:
      - "4200:4200"
    depends_on:
      - model-service
    environment:
      - MODEL_SERVICE_URL=model-service
      - MODEL_SERVICE_PORT=5050
    networks:
      - app-network

  model-service:
    build:
      context: ../model-service
    container_name: model_container
    ports:
      - "5050:5050"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
