services:
  app:
    container_name: app_container
    image: ${APP_NAME}:${APP_VERSION}
    restart: unless-stopped # Restart Policy: Restart unless explicitly stopped (best for development/production)
    depends_on:
      - model-service
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DNS=model-service
      - MODEL_PORT=${MODEL_PORT}
    networks:
      - app-network

  model-service:
    container_name: model_service_container
    image: ${MODEL_NAME}:${MODEL_VERSION}
    restart: unless-stopped
    environment:
      - MODEL_SERVICE_PORT=${MODEL_PORT}
    expose:
      - "${MODEL_PORT}" # Internal only
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
