apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ printf "%s-%s" .Values.releaseNamePrefix .Values.rateLimit.name }}
  namespace: {{ .Values.rateLimit.namespace }}
spec:
  workloadSelector:
    labels:
      istio: {{ .Values.rateLimit.selector.istio }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          portNumber: {{ .Values.rateLimit.portNumber }}
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: {{ printf "%s-%s" .Values.releaseNamePrefix .Values.rateLimit.statPrefix }}
            token_bucket:
              max_tokens: {{ .Values.rateLimit.maxTokens }}
              tokens_per_fill: {{ .Values.rateLimit.tokensPerFill }}
              fill_interval: {{ .Values.rateLimit.fillInterval }}
            filter_enabled:
              runtime_key: {{ .Values.rateLimit.runtimeKeys.enabled }}
              default_value:
                numerator: {{ .Values.rateLimit.defaultValue.numerator }}
                denominator: {{ .Values.rateLimit.defaultValue.denominator }}
            filter_enforced:
              runtime_key: {{ .Values.rateLimit.runtimeKeys.enforced }}
              default_value:
                numerator: {{ .Values.rateLimit.defaultValue.numerator }}
                denominator: {{ .Values.rateLimit.defaultValue.denominator }}
            response_headers_to_add:
              - append: false
                header:
                  key: {{ .Values.rateLimit.responseHeader.key }}
                  value: {{ .Values.rateLimit.responseHeader.value | quote }}
