apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-app-servicemonitor" .Values.releaseNamePrefix }}
  namespace: monitoring
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      app: {{ printf "%s-app" .Values.releaseNamePrefix }}
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.namespace }}
  endpoints:
    - port: {{ .Values.monitoring.metrics.portName }}
      path: {{ .Values.monitoring.metrics.path }}
      interval: {{ .Values.monitoring.metrics.interval }}
