---
- hosts: 192.168.56.100
  become: yes
  tasks:

    # --- Undo MetalLB ---
    - name: Delete Layer 2 advertisement
      command: kubectl delete -f /vagrant/provisioning/l2advertisement.yml --ignore-not-found

    - name: Delete IP address pool
      command: kubectl delete -f /vagrant/provisioning/ipaddresspool.yml --ignore-not-found

    - name: Delete MetalLB native manifest
      command: kubectl delete -f https://raw.githubusercontent.com/metallb/metallb/v0.14.7/config/manifests/metallb-native.yaml --ignore-not-found

    # --- Undo ingress-nginx Helm release ---
    - name: Uninstall ingress-nginx Helm release
      kubernetes.core.helm:
        name: ingress-nginx
        namespace: ingress-nginx
        state: absent

    # --- Undo Kubernetes Dashboard ---
    - name: Delete dashboard ingress
      command: kubectl delete -f /vagrant/provisioning/dashboard-ingress.yml --ignore-not-found

    - name: Delete dashboard admin ServiceAccount and ClusterRoleBinding
      command: kubectl delete -f /vagrant/provisioning/dashboard-admin.yml --ignore-not-found

    - name: Uninstall kubernetes-dashboard Helm release
      kubernetes.core.helm:
        name: kubernetes-dashboard
        namespace: kubernetes-dashboard
        state: absent

    - name: Delete kubernetes-dashboard namespace
      command: kubectl delete namespace kubernetes-dashboard --ignore-not-found

    # --- Undo Istio ---
    - name: Uninstall Istio with istioctl
      command: istioctl uninstall --purge --skip-confirmation
      ignore_errors: yes

    - name: Remove Istio directory
      file:
        path: /opt/istio-1.25.2
        state: absent

    - name: Remove istioctl symlink
      file:
        path: /usr/local/bin/istioctl
        state: absent

    # --- Undo Prometheus kube-prometheus-stack ---
    - name: Uninstall prometheus-operator Helm release
      ansible.builtin.shell: helm uninstall prometheus-operator --namespace monitoring
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      ignore_errors: yes

    - name: Delete monitoring namespace
      command: kubectl delete namespace monitoring --ignore-not-found
