- name: Join worker node to Kubernetes cluster
  hosts: worker
  become: yes
  vars:
    kube_config_path: /etc/kubernetes/admin.conf

  tasks:
    - name: Generate the kubeadm join command on the controller
      command: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_command_output

    - name: Run the join command on the worker node
      shell: "{{ join_command_output.stdout }}"
      environment:
        KUBECONFIG: "{{ kube_config_path }}"
