{
 "title": "team18",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Validation Duration per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(duration_validation_req{job=\"team18-app\", version=\"v1.0\"}\n  and on(version)\n  (\n    duration_validation_req{job=\"team18-app\", version=\"v1.0\"}\n    != duration_validation_req{job=\"team18-app\", version=\"v1.0\"} offset 20s\n  )\n)\nor\n(\n  duration_validation_req{job=\"team18-app\", version=\"v1.0\"}\n  unless duration_validation_req{job=\"team18-app\", version=\"v1.0\"} offset 20s\n)",
     "legendFormat": "Condition A"
    },
    {
     "expr": "(duration_validation_req{job=\"team18-app\", version=\"v2.0\"}\n  and on(version)\n  (\n    duration_validation_req{job=\"team18-app\", version=\"v2.0\"}\n    != duration_validation_req{job=\"team18-app\", version=\"v2.0\"} offset 20s\n  )\n)\nor\n(\n  duration_validation_req{job=\"team18-app\", version=\"v2.0\"}\n  unless duration_validation_req{job=\"team18-app\", version=\"v2.0\"} offset 20s\n)",
     "legendFormat": "Condition B"
    }
   ]
  },
  {
   "title": "Stat panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_reqs{job=\"team18-app\"})",
     "legendFormat": "Prediction Request Count"
    },
    {
     "expr": "sum(count_preds{job=\"team18-app\"})",
     "legendFormat": "Prediction Assessment Request Count"
    },
    {
     "expr": "sum(count_correct_preds{job=\"team18-app\"})",
     "legendFormat": "Correct Prediction Count"
    },
    {
     "expr": "sum(count_incorrect_preds{job=\"team18-app\"})",
     "legendFormat": "Incorrect Prediction Count"
    }
   ]
  },
  {
   "title": "Average Prediction Correction Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duration_validation_req{job=\"team18-app\", version=\"v1.0\"}",
     "legendFormat": "Condition A"
    },
    {
     "expr": "duration_validation_req{job=\"team18-app\", version=\"v2.0\"}",
     "legendFormat": "Condition B"
    }
   ]
  },
  {
   "title": "Average Duration of Model Prediction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(duration_pred_req{job=\"team18-app\"})",
     "legendFormat": "Condition A"
    }
   ]
  },
  {
   "title": "Prediction Correction Duration Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "duration_validation_req{job=\"team18-app\", version=\"v1.0\"}",
     "legendFormat": "Condition A"
    },
    {
     "expr": "duration_validation_req{job=\"team18-app\", version=\"v2.0\"}",
     "legendFormat": "Condition B"
    }
   ]
  },
  {
   "title": "Heatmap panel",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "hist_duration_pred_req{job=\"team18-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time series panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(count_preds{job=\"team18-app\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(count_reqs{job=\"team18-app\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}