apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: team18-app-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: team18-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
