# app.yaml
apiVersion: apps/v1
kind: Deployment
# A Deployment manages a set of Pods to run an application workload
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template: # all pods will be created from this template
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/remla25-team18/app:0.0.7
          ports:
            - containerPort: 4200
          envFrom:
            - configMapRef:
                name: app-config

      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 4200
      targetPort: 4200
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  
  APP_SERVICE_VERSION: "0.0.7"
  port: "4200"
  host: "0.0.0.0"
