apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: team18-app-servicemonitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: team18-app
  endpoints:
  - port: web
    path: /metrics 
    interval: 1s
