apiVersion: v1
kind: Service
metadata:
  name: team18-app
spec:
  type: NodePort
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30001
  selector:
    app: team18-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: team18-app-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: team18-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
