releaseNamePrefix: team18

app:
  replicaCount: 1
  image:
    repository: ghcr.io/remla25-team18/app
    tag: "0.0.7"
    pullPolicy: IfNotPresent
  env:
    MODEL_SERVICE_URL: team18-model-service
    MODEL_SERVICE_PORT: "5050"

model:
  replicaCount: 1
  image:
    repository: ghcr.io/remla25-team18/model-service
    tag: "1.0.2"
    pullPolicy: Always
  servicePort: 5050

monitoring:
  appService:
    nodePort: 30001
    port: 9090
    targetPort: 9090
