- name: Cluster Configuration for ctrl Node
  hosts: 192.168.56.100
  become: yes
  tasks:    

    # Creating pods and services for the model and app, setting up monitoring and ingress
    - name: Apply Kubernetes yml files
      shell: |
        kubectl apply -f /vagrant/k8s/model.yaml
        kubectl apply -f /vagrant/k8s/app.yaml
        kubectl apply -f /vagrant/k8s/monitoring.yaml
        kubectl apply -f /vagrant/k8s/ingress.yaml
        kubectl apply -f /vagrant/k8s/istio-rate-limit.yaml
        kubectl apply -f /vagrant/k8s/istio-ingress.yaml
        kubectl apply -f /vagrant/k8s/istio-fixed-ip.yaml

    - name: Auto load Grafana
      shell: kubectl apply -f /vagrant/k8s/dashboard-configmap.yaml