- name: Finalization Step for ctrl Node
  hosts: 192.168.56.100
  become: yes
  vars:
    manifest_base: /vagrant/provisioning/manifests
  tasks:

    # Step 20: MetalLB Installation
    - name: Install MetalLB native manifest
      command: kubectl apply -f {{ manifest_base }}/metallb/metallb-native-0.14.9.yml

    - name: Wait for MetalLB controller to be ready
      shell: >
        kubectl wait -n metallb-system \
        -l app=metallb,component=controller \
        --for=condition=ready pod \
        --timeout=60s
      register: wait_metallb
      retries: 5
      delay: 10
      until: wait_metallb.rc == 0

    - name: Add IP address pool if not already applied
      command: kubectl apply -f {{ manifest_base }}/metallb/ipaddresspool.yml

    - name: Add Layer 2 advertisement if not already applied
      command: kubectl apply -f {{ manifest_base }}/metallb/l2advertisement.yml

    # Step 21: Nginx Ingress
    - name: Add ingress-nginx Helm repo and update cache
      kubernetes.core.helm_repository:
        name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
        state: present

    - name: Install ingress-nginx with Helm
      kubernetes.core.helm:
        release_name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        namespace: ingress-nginx
        create_namespace: true
        values:
          controller:
            service:
              loadBalancerIP: 192.168.56.90
        state: present
        wait: true
  
    # Step 22: Kubernetes Dashboard
    - name: Add Kubernetes Dashboard Helm repository
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard/

    - name: Install Kubernetes Dashboard via Helm
      kubernetes.core.helm:
        name: kubernetes-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        namespace: kubernetes-dashboard
        create_namespace: true

    - name: Apply admin-user ServiceAccount and ClusterRoleBinding
      command: kubectl apply -f /vagrant/provisioning/manifests/dashboard/dashboard-admin.yml

    - name: Apply Ingress for Kubernetes Dashboard
      command: kubectl apply -f /vagrant/provisioning/manifests/dashboard/dashboard-ingress.yml

    # Other tasks
    - name: Ensure team18-tls secret exists (recreate if needed)
      shell: |
        if kubectl get secret team18-tls &>/dev/null; then
          kubectl delete secret team18-tls
        fi
        kubectl create secret tls team18-tls \
          --cert=/vagrant/tls/tls.crt \
          --key=/vagrant/tls/tls.key
      args:
        executable: /bin/bash

    # Other tasks
    - name: Ensure team18-tls secret exists (recreate if needed)
      shell: |
        if kubectl get secret team18-tls &>/dev/null; then
          kubectl delete secret team18-tls
        fi
        kubectl create secret tls team18-tls \
          --cert=/vagrant/tls/tls.crt \
          --key=/vagrant/tls/tls.key
      args:
        executable: /bin/bash

    # Enabling Prometheus
    - name: Add Prometheus Community Helm repo
      ansible.builtin.shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      environment:
        KUBECONFIG: /home/vagrant/.kube/config

    - name: Update Helm repos
      ansible.builtin.shell: helm repo update
      environment:
        KUBECONFIG: /home/vagrant/.kube/config

    - name: Install kube-prometheus-stack (includes Prometheus Operator)
      ansible.builtin.shell: helm install prometheus-operator prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
      environment:
        KUBECONFIG: /home/vagrant/.kube/config