- name: Finalization Step for ctrl Node
  hosts: 192.168.56.100
  become: yes
  vars:
    manifest_base: /vagrant/provisioning/manifests
  tasks:

    # Step 20: MetalLB Installation
    - name: Install MetalLB native manifest
      command: kubectl apply -f {{ manifest_base }}/metallb/metallb-native-0.14.9.yml

    - name: Wait for MetalLB controller to be ready
      shell: >
        kubectl wait -n metallb-system \
        -l app=metallb,component=controller \
        --for=condition=ready pod \
        --timeout=60s
      register: wait_metallb
      retries: 5
      delay: 10
      until: wait_metallb.rc == 0

    - name: Add IP address pool if not already applied
      command: kubectl apply -f {{ manifest_base }}/metallb/ipaddresspool.yml

    - name: Add Layer 2 advertisement if not already applied
      command: kubectl apply -f {{ manifest_base }}/metallb/l2advertisement.yml

    # Step 21: Nginx Ingress
    - name: Add ingress-nginx repo
      command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update helm repo
      command: helm repo update

    - name: Install ingress-nginx with helm
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        namespace: ingress-nginx
        create_namespace: true
        values:
          controller:
            service:
              loadBalancerIP: 192.168.56.90

    # Step 22: Kubernetes Dashboard
    - name: Add Kubernetes Dashboard Helm repository
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard/

    - name: Install Kubernetes Dashboard via Helm
      kubernetes.core.helm:
        name: kubernetes-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        namespace: kubernetes-dashboard
        create_namespace: true

    - name: Wait for ingress-nginx admission webhook to be ready
      shell: >
        kubectl wait --namespace ingress-nginx
        --for=condition=ready pod
        --selector=app.kubernetes.io/component=controller
        --timeout=90s
      register: wait_webhook
      retries: 5
      delay: 10
      until: wait_webhook.rc == 0

    - name: Create admin user account for Dashboard
      command: kubectl apply -f {{ manifest_base }}/dashboard/dashboard-admin.yml

    - name: Apply Ingress for Kubernetes Dashboard
      command: kubectl apply -f {{ manifest_base }}/dashboard/dashboard-ingress.yml