- name: Basic setup for all nodes
  hosts: all
  become: yes
  vars:
    manifest_base: /vagrant/provisioning/manifests
  tasks:
    - name: Set up multiple authorized keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop:
        - "../ssh-keys/lemon.pub"
        - "../ssh-keys/madalena.pub"
        - "../ssh-keys/laszlo.pub"
        - "../ssh-keys/yahor.pub"

    - name: Update apt package index
      apt: update_cache=yes

    - name: Install basic tools
      apt:
        name: ["curl", "wget", "apt-transport-https"]
        state: present

    - name: Add signing key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        state: present

    - name: Add kubernetes repository
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
        state: present
        filename: kubernetes.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install containerd
      ansible.builtin.apt:
        name: containerd=1.7.24-0ubuntu1~24.04.2
        state: present

    - name: Install runc
      ansible.builtin.apt:
        name: runc=1.1.12-0ubuntu3
        state: present
        allow_downgrade: yes

    
    # do "vagrant ssh ctrl" for example
    # and check versions with "apt-cache policy containerd"
    # so that the version to be installed is the same as the one in the apt-cache policy
    - name: Install Kubernetes tools
      ansible.builtin.apt:
        name:
          - kubeadm=1.32.4-1.1
          - kubelet=1.32.4-1.1
          - kubectl=1.32.4-1.1
        state: present

    - name: Ensure containerd config dir exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    # do "vagrant ssh ctrl" for example
    # and check the content of the file with "cat /etc/containerd/config.toml"
    - name: Disable AppArmor
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*disable_apparmor'
        line: "disable_apparmor = true"
        state: present
        backup: yes

    - name: Update sandbox image version
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*sandbox_image'
        line: 'sandbox_image = "registry.k8s.io/pause:3.10"'
        state: present
        backup: yes

    - name: Setup systemd cgroup
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*SystemdCgroup'
        line: "SystemdCgroup = true"
        state: present
        backup: yes

    - name: Restart containerd service
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: yes

    - name: Enable kubelet on boot
      ansible.builtin.service:
        name: kubelet
        enabled: yes
        state: started

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Create module config dir
      file:
        path: /etc/modules-load.d
        state: directory
        mode: "0755"

    - name: Copy kernel module config
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: "0644"

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Configure sysctl for k8s
      copy:
        dest: /etc/sysctl.d/99-kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
      notify: reload sysctl
      
    - name: Apply sysctl config immediately
      command: sysctl --system

    - name: Manage /etc/hosts with Jinja2
      ansible.builtin.template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"

  handlers:
    - name: reload sysctl
      command: sysctl --system
