# This files stores the variables used in the Helm chart for deploying the application and its components.

releaseNamePrefix: team18

app:
  image:
    repository: ghcr.io/remla25-team18/app
    pullPolicy: IfNotPresent
  imagePullSecret: ghcr-secret
  containerPort: 4200
  servicePort: 80
  replicaCount: 1
  env:
    MODEL_SERVICE_URL: team18-model-service
    MODEL_SERVICE_PORT: 5050
  versions:
    v1:
      tag: 0.0.18
    v2:
      tag: 0.0.19

model:
  replicaCount: 1
  image:
    repository: ghcr.io/remla25-team18/model-service
    tag: 1.0.3
    pullPolicy: Always
  servicePort: 5050

monitoring:
  namespace: default
  releaseLabel: prometheus
  metrics:
    portName: metrics
    path: /metrics
    interval: 15s
